// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentApi.Model;

#nullable disable

namespace PaymentApi.Migrations
{
    [DbContext(typeof(PaymentDetailContext))]
    partial class PaymentDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PaymentApi.Model.Paymentdetail", b =>
                {
                    b.Property<int>("PaymentdetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaymentdetailId"));

                    b.Property<string>("CardNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("CardOwnerName")
                        .HasColumnType("longtext");

                    b.Property<string>("ExpirationDate")
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityCode")
                        .HasColumnType("longtext");

                    b.HasKey("PaymentdetailId");

                    b.ToTable("Paymentdetails");
                });
#pragma warning restore 612, 618
        }
    }
}
